### ISSUE TITLE
How to support aarch64

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/xopen-feedstock#31]
### Comment:

Although `xopen` has been added in [conda-forge-pinning-feedstock/recipe/migrations/arch_rebuild.txt](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/0b8b0f3ce222f4a09afa921f780b8b38f4d1afea/recipe/migrations/arch_rebuild.txt#L912), why is the build of aarch64 not triggered? How can aarch64 be supported? Thanks.

**Comment by rhpvorderman** [comment]
I have no clue as to why this is the case. You could try and make a PR to rebuild for aarch64 yourself. Alternatively you can use pip to install xopen. It should work on aarch64

**Comment by yangxingyu588** [comment]
yes, but there's nothing [here](https://anaconda.org/search?q=xopen) about `xopen` `aarch64` or `noarch `above 1.0.

**Comment by yangxingyu588** [comment]
@rhpvorderman What ideas or plans do you have on this subject? Thank you.

**Comment by marcelm** [comment]
Sorry, but I don’t know how to proceed. I don’t even know what the `arch_rebuild.txt` file is for.

**Comment by yangxingyu588** [comment]
Hi @martin-g Do you have any good ideas,`arch_rebuild.txt` file already exists, does it seem that we need to manually modify the source code?

**Comment by martin-g** [comment]
When a package is added to arch_rebuild.txt then a bot creates a PR like https://github.com/conda-forge/jags-feedstock/pull/12 with a title `Arch Migrator`.
I see no such PR here. Maybe the bot was/is broken ?!
@mfansler Do you have an idea ?

**Comment by mfansler** [comment]
@martin-g the information on migrator bot status is collected automatically and summarized at on [the Conda Forge Status page](https://conda-forge.org/status/). Here is specifically the Arch migrator section: https://conda-forge.org/status/#aarch64andppc64leaddition.  It currently shows that `xopen` is classified as "Awaiting Parents", specifically, one needs to first see successful migrations of:

- `pbzip2`: https://github.com/conda-forge/pbzip2-feedstock/pull/7
- `pigz`: https://github.com/conda-forge/pigz-feedstock/pull/17
- `pyqt`: https://github.com/conda-forge/pyqt-feedstock/pull/99

The `pyqt` is weird, since that does appear to have merged a while ago and is successfully [building `aarch64` and `ppc64le` builds](https://github.com/conda-forge/pyqt-feedstock/runs/17056258935). Otherwise, if you are hoping to help along, the other two appear to need work.

@beckermr looks another migrator bot issue here. Should I file a separate bug report somewhere?

**Comment by martin-g** [comment]
I've created https://github.com/conda-forge/pigz-feedstock/pull/18 for the `pigz` issue!

**Comment by marcelm** [comment]
And I’m working an pbzip2 over at https://github.com/conda-forge/pbzip2-feedstock/pull/8
